### ISSUE TITLE
Attribute error: add, subtract, multiply, divide by SymPy real 

### ISSUE THREAD

**Issue by FredLunnon** [arsenovic/clifford#4]
# cd /Users/fred/fred/clifford-master; python
# Instantiate algebra and unit vectors

from clifford import *; 
p,q,r = 2,0,0;  # r = 0 ! 
GAlayout, GAblades = Cl(p, q); 
(e0, e1) = ( GAblades[GAlayout.names[k+1]] for k in range(0, p+q) ); 
# Bug in add, subtract, multiply, divide by SymPy real: attribute error

from sympy import sqrt; 
e1/e1.mag2();  # e1 OK! 
e1/sqrt(e1.mag2());  # AttributeError: 'One' object has no attribute 'inv' 
e1*sqrt(e1.mag2());  # ditto 
sqrt(e1.mag2()) + e1;  # ditto 
e1 - sqrt(e1.mag2());  # ditto

**Comment by FredLunnon** [comment]
On second thoughts, probably related to Issue 2 ?

**Comment by moble** [comment]
Functions from `sympy` should generally only be used with `sympy`, unless you're "exporting" expressions, for which specific `sympy` functions are needed — like `lambidfy`, `ufuncify`, `codegen`, etc.

The quantity returned by `e1.mag2()` is a numpy float or (as in this case) int:
```python
>>> type(e1.mag2())
numpy.int64
```
So you want something that will operate on that.  For example
```python
from math import sqrt
```
or
```python
from numpy import sqrt
```
(The former is usually a teensy bit faster if you're just finding the sqrt of a single number.)

On the other hand, in `_checkOther`, it might be good to add a statement [here](https://github.com/arsenovic/clifford/blob/master/clifford/__init__.py#L604) to see if the object has a `__float__` attribute or maybe `evalf`, and use it if desired
```python
        elif hasattr(other, '__float__'):
            if coerce:
                # sympy scalar
                newOther = self._newMV()
                newOther[()] = other.__float__()
                return newOther, True
            else:
                return other, False
```

**Comment by FredLunnon** [comment]
Temporary workaround: 

`Z = MultiVector(GAlayout); Z.value[0] = sqrt(e1.mag2());  
e1 + Z; # OK 
`

**Comment by moble** [comment]
But why don't you just import `sqrt` from something meant for numerics
(i.e., not sympy)?

If you want to also use sympy's version in the same code and avoid a name
clash, you could do something like this:

```
from sympy import sqrt
from math import sqrt as msqrt

e1 + msqrt(e1.mag2())
```

**Comment by FredLunnon** [comment]
On 9/11/16, Mike Boyle <notifications@github.com> wrote:
> But why don't you just import `sqrt` from something meant for numerics
> (i.e., not sympy)?
> 
> If you want to also use sympy's version in the same code and avoid a name
> clash, you could do something like this:
> 
> ```
> from sympy import sqrt
> from math import sqrt as msqrt
> 
> e1 + msqrt(e1.mag2())
> ```

  That's fine in this case, agreed.  But I'm looking ahead to similar situations 
where a temporary fix is required while AA considers how to sort it out properly. 
By the look of things, another will arise very soon ... 

> 
> On Sun, Sep 11, 2016 at 9:10 AM FredLunnon <notifications@github.com>
> wrote:
> 
>> Temporary workaround:
>>
>> Z = MultiVector(GAlayout); Z.value[0] = sqrt(e1.mag2());
>> e1 + Z; # OK
>>

**Comment by moble** [comment]
> That's fine in this case, agreed. But I'm looking ahead to similar situations 
> where a temporary fix is required while AA considers how to sort it out properly.

I don't know what other situations you're talking about, but as a very general rule, you should ***NEVER*** use sympy functions when you're doing numerics.  Sympy is for *symbolic* python; numpy is for *numeric* python.  The two don't mix.  Sympy's functions are far slower and return the wrong data types for numpy (which is what `clifford` uses).

You can even see this in the error message you quoted above:

    AttributeError: 'One' object has no attribute 'inv'

`One` is a sympy object that *you* passed in, which screwed things up.  If you print out `sqrt(e1.mag2())` it looks like `1`, but if you print `type(sqrt(e1.mag2()))` it's `sympy.core.numbers.One`.  It seems that the "proper" way to sort this out is for *you* to use numeric functions.  The code will be slowed further if it needs to check for bizarre data types at every turn.

**Comment by FredLunnon** [comment]
I wouldn't want to disagree with anything above; however, I feel bound to point out 
that saving a few nanoseconds on a real square root is, in the grand scheme of things, 
hardly a major concern at this stage of the project --- see eg. issue 2 !  Also your 
analysis does not clarify why inserting the value directly into  Z  is successful. 

  [ Why was I perversely importing from  <sympy>  rather than  <numpy>  anyway?  
A call for  floor()  elsewhere in the program was returning a double instead of an integer. 
I changed  <numpy>  to  <sympy>  as a quick fix.  And promptly broke  sqrt() . ] 

  Catch 22 ...  Seriously,  I have to date spent longer attempting to convert working  
<GAlgebra>  code to  <clifford> , than implementing  <ClifFred>  from scratch and 
then converting to that.  I'm afraid that  <clifford>  remains some distance away from 
a state where a casual user could program in it with any expectation of success.

**Comment by FredLunnon** [comment]
[Previous message scrambled by the editor.  Trying again.] 

I wouldn't want to disagree with anything above; however, I feel bound to point out
that saving a few nanoseconds on a real square root is, in the grand scheme of things,
hardly a major concern at this stage of the project --- see eg. issue 2 !  Also your
analysis does not clarify why inserting the value directly into Z is successful.

[ Why was I perversely importing from  NumPy  rather  SymPy  than anyway? 
A call for floor() elsewhere in the program was returning a double instead of an integer.
I changed  NumPy  to  SymPy  as a quick fix. And promptly broke sqrt() . ]

Catch 22 ... Seriously, I have to date spent longer attempting to convert working 
GAlgebra  code to  clifford , than implementing  ClifFred  from scratch and
then converting to that. I'm afraid that  clifford  remains some distance away from
a state where a casual user could program in it with any expectation of success.

**Comment by moble** [comment]
> saving a few nanoseconds on a real square root is, in the grand scheme of things, hardly a major concern at this stage of the project --- see eg. issue 2 !

Sure.  But imagine if, in the millions of computations your code in issue 2 is asking for, each computation had to check its input types.  The problem would be much worse.  So I think this issue is a non-issue, and should be closed.

> Also your analysis does not clarify why inserting the value directly into Z is successful.

Look at the code called by each operation.  Your first example died at [line 759 of `__div__`](https://github.com/arsenovic/clifford/blob/master/clifford/__init__.py#L759), so you can see what goes wrong.  In your second example, inserting the value into Z changes the value of an element in a numpy `float` array.  For memory safety, numpy [always converts the argument of that expression to a `float`](https://github.com/numpy/numpy/blob/1429c606643d1ad305e710c4a31cb6f398d04c53/numpy/lib/user_array.py#L57), which makes sense generally, and works correctly with `One`.  But there's not what `__div__` should do, because some of its arguments cannot be correctly cast to `float`.

> I have to date spent longer attempting to convert working GAlgebra code to clifford , than implementing ClifFred from scratch and then converting to that.

My two cents: galgebra is closely tailored to symbolics, and not to performance.  For example, there are really clever things involving bit-twiddling that could be done for numerics (see ch. 19 of [Dorst et al.](http://www.geometricalgebra.net/index.html), but note that some simple generalizations are needed for more general signatures) that don't make much sense for `galgebra`, but do make sense for any numerical GA code.  It seems like a bad idea to try to directly translate `galgebra` except to have a distinct implementation for comparison in testing.

**Comment by arsenovic** [comment]
fred, 
     trying to support  sympy functions in a numerical package does not make sense, and i think we all are in agreement on this. there are several bugs in clifford, for sure, and i appreciate you working on it. 

 if  creating your own package from scratch is faster, i think that makes sense. you will certainly learn a lot . if you choose to go that route and have hopes that others use your work, i would suggest you look at some python coding style guidelines and example projects.   

personally, i would like to see some common algebras (G2 G3 G3,1 G4,1) supported  in numpy, with ability to translate from galgebra. this obviously requires more work and organisation ability than i have available, but i think its a good end-goal.

**Comment by FredLunnon** [comment]
I was trying to achieve two things by converting existing programs to use _clifford_ 
(still grappling with github editor here) --- firstly, to compare the performance of my 
own package with existing ones; secondly, to try to make the algorithms I designed for 
frame transform and Givens' factoring available to Alex, who proposed them in the 
first place. 

  Regarding special algebras, Brombo mentioned _Glucat_ + _pyclical_ wrappers: 
there are detailed installation instructions, but I don't currently feel up to taking 
them on ...  I have in the past written optimised Maple packages for 
Cl(3,0,1), Cl(3,2), Cl(4,2).  My experiments with Cl(12) etc are purely for testing 
performance and theoretical conjectures: I know of no applications for algebras 
of grade exceeding (I think) 8. 

  Re issue #2 --- apologies, I meant issue #3 (slow initialisation), where type checking 
is not relevant.  The big consumers of time are initialisation, products, and (general) 
inversion, where any type checking would only be required on entry. 

WFL
