### ISSUE TITLE
Loading error when installed with pip

### ISSUE THREAD

**Issue by rahulsidhu** [arsenovic/clifford#8]
I just installed the package (v 0.8) using pip, loaded some example code:
`from numpy import e, pi
from clifford.g3 import *  # import GA for 3D space`

and got an error:
 `../python3.6/site-packages/clifford/__init__.py", line 306`
 `   raise ValueError, "names list of length %i needs to be of length %i"% (len(names), self.gaDims)`
`                    ^`
`SyntaxError: invalid syntax`

Unable for format it right but the error points to the comma after `raise ValueError`
Seems the package might be a bit outdated?

**Comment by arsenovic** [comment]
yes, i think that the build is old. we can leave this issue open, so i remember to make a release, but if you want to use the up-to-date version download the github zip, or git repo.

**Comment by ereide** [comment]
Really like your library and use it in extensively in my research. But would be helpful to have it install correctly with pip to make it more portable. Is there any way you could get around to doing this?

**Comment by arsenovic** [comment]
i just uploaded v0.81, try that .  i will put this on conda forge eventually.

**Comment by arsenovic** [comment]
can we close this?

**Comment by rahulsidhu** [comment]
Just checked, works fine for me now.

**Comment by ereide** [comment]
Thank you!
