### ISSUE TITLE
Refuses to operate on MultiVectors with identical Layout objects

### ISSUE THREAD

**Issue by hugohadfield** [arsenovic/clifford#9]
Comparison in MultiVector._checkOther compares ids of layout objects rather than contents of the layout instead. This is a problem when operating with instances of the algebra created with copy.deepcopy() applied to the MultiVector as the contents of the layouts will be the same but the ids of the objects will be different. A quick hack fix is to implement an __eq__ and __ne__ method for the layout class:

    def __eq__(self, other):
      return self.__str__() == other.__str__()
    def __ne__(self, other):
      return not self.__eq__(other)

and change MultiVector._checkOther to use != rather than 'is not'.

Obviously getting the layout as a string and comparing these values is not the best serialisation and comparison scheme. Any detailed comparison of the full contents of the class is likely to affect performance somewhat but I think some kind of comparison of core pieces of information from the layout would be worthwhile instead of the id comparison currently used.

**Comment by arsenovic** [comment]
good point. seems to me that all you need to know is the signature to ensure the GA is the same, so we should be able to do `self.layout.sig == other.layout.sig`,
see any problems with this?

**Comment by hugohadfield** [comment]
Sure, so the overwritten __eq__ and __ne__ operatorsw in Layout should become:
    def __eq__(self, other):
      return np.all(self.sig == other.sig)

    def __ne__(self, other):
      return not self.__eq__(other)

**Comment by arsenovic** [comment]
yeah that makes sense to me.

**Comment by arsenovic** [comment]
do you want to submit a PR? or i can do it,

**Comment by hugohadfield** [comment]
Yeah I was just looking at that! Probably easiest if you do it as I have messed up my local copy of the repo quite a lot...

**Comment by arsenovic** [comment]
yeah  i hear ya, no prob

**Comment by arsenovic** [comment]
let me know if this works for you , 
 https://github.com/arsenovic/clifford/commit/deb9648401f07ca6c5f22745d2055eb456095dca

**Comment by hugohadfield** [comment]
Perfect, thanks :)
